[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "hide_and_shreak"
version = "0.1.0"
description = "A Python roguelike demo where your only objective is survival"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "esper>=3.4",
    "numpy>=2.3.5",
    "pygame>=2.6.1",
    "tcod>=19.6.0",
]

[project.scripts]
hide-and-shreak = "src.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src"]